# -*- coding: utf-8 -*-
"""LVADSUSR147_Duvvapu_Chinni_Vaishnavi147.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1quC4hTfnXSaZhEy0Ntj4HvUk4tlGdrUR
"""

#1
import pandas as pd
d=pd.read_csv("/content/sample_data/Final Dataset - IPL.csv")
missing=pd.isna(d)
missing_count=missing.count()
print("Missing values status",missing)
print("Count of missing values",missing_count)
print("Number of elements",d.size)
print("Number of rows and columns",d.shape)
print("Type of data",type(d))
d.info()
d.describe()

#2
import pandas as pd
d=pd.read_csv("/content/sample_data/Final Dataset - IPL.csv")
missing=pd.isna(d)
missing_count=missing.count()
print(missing_count)
d.fillna(0,inplace=True)
#as there are more number of missing values dropping rows may impact the data.So i filled the missing values with zeros.
print("Duplicates",d.duplicated())
print("Count of duplicate values",d.duplicated().sum())
#there are no duplicate values

#3
import pandas as pd
d=pd.read_csv("/content/sample_data/Final Dataset - IPL.csv")
#I am analyzing the column "highscore"
mean=d["highscore"].mean()
print("Mean is",mean)
median=d["highscore"].median()
print("Median is",median)
mode=d["highscore"].mode()
print("Mode is",mode)
standard_deviation=d["highscore"].std()
print("Standard deviation is",standard_deviation)

#4
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
d=pd.read_csv("/content/sample_data/Final Dataset - IPL.csv")
plt.figure(figsize=(12, 5))
d['won_by'].value_counts().plot.pie(autopct='%1.1f%%')
plt.title('Runs vs Wickets')
plt.legend()
plt.show()
sns.barplot(data=d,x="team1",y="highscore")
plt.title("Team vs Highscores")
plt.show()
plt.grid()
plt.xticks(rotation=90)
sns.histplot(x="margin",edgecolor="black",data=d)
plt.title("Count of margin")
plt.show()

#5
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
d=pd.read_csv("/content/sample_data/Final Dataset - IPL.csv")
plt.figure(figsize=(5,5))
sns.scatterplot(x="toss_decision",y="first_ings_score",data=d)
plt.title("Toss decision vs first innings score")
plt.show()
plt.grid()
plt.legend()
sns.scatterplot(x="venue",y="match_winner",data=d)
plt.title("Venue vs match winner")
plt.xticks(rotation=45)
plt.grid()
plt.legend()
d.corr()

#6
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
d=pd.read_csv("/content/sample_data/Final Dataset - IPL.csv")
plt.figure(figsize=(5, 5))
np.random.seed(10)
D = np.random.normal((3, 5, 4), (1.25, 1.00, 1.25), (100, 3))
fig, ax = plt.subplots()
VP = ax.boxplot(D, positions=[2, 4, 6], widths=1.5, patch_artist=True,
                showmeans=False, showfliers=False,
                medianprops={"color": "white", "linewidth": 0.5},
                boxprops={"facecolor": "C0", "edgecolor": "white",
                          "linewidth": 0.5},
                whiskerprops={"color": "C0", "linewidth": 1.5},
                capprops={"color": "C0", "linewidth": 1.5})

ax.set(xlim=(0, 8), xticks=np.arange(1, 8),
       ylim=(0, 8), yticks=np.arange(1, 8))

plt.show()

# I want to remove the outliers because these are sevrely effecting my data.So instead of handling i am removing the outliers.

#7
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
d=pd.read_csv("/content/sample_data/Final Dataset - IPL.csv")
a=d.groupby("venue").agg({"match_winner":"count"}).sort_values( by="match_winner",ascending=False)
print(a)
v=d.groupby("venue").agg({"player_of_the_match":"count"}).sort_values( by="player_of_the_match",ascending=False)
print(v)
#Wankhede Stadium, Mumbai  gave the highset number of wins while Narendra Modi Stadium, Ahmedabad  gave the least number of wins

#8
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
d=pd.read_csv("/content/sample_data/Final Dataset - IPL.csv")
playerofthematch=d["best_bowling"].sum()
print(playerofthematch)
bestbowler=d.groupby("best_bowling").agg({"best_bowling":"count"})
print(bestbowler)

#9
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
d=pd.read_csv("/content/sample_data/Final Dataset - IPL.csv")
plt.figure(figsize=(12, 5))
plt.subplot(3,1,1)
d['won_by'].value_counts().plot.pie(autopct='%1.1f%%')
plt.title('Runs vs Wickets')
plt.legend()
plt.show()
plt.subplot(5,1,1)
sns.barplot(data=d,x="team1",y="highscore")
plt.title("Teanm vs Highscores")
plt.show()
plt.grid()
plt.subplot(5,1,2)
sns.histplot(x="margin",edgecolor="black",data=d)
plt.title("Count of different margins")
plt.show()
plt.subplot(5,1,3)
sns.scatterplot(x="toss_decision",y="first_ings_score",data=d)
plt.show()
plt.grid()
plt.legend()
plt.subplot(5,1,4)
sns.scatterplot(x="venue",y="match_winner",data=d)
plt.grid()
plt.xticks(rotation=45)
plt.legend()
#My analysis and insights
#Number of elements in the dataset is  1480
#Number of rows and columns  in the datset is (74, 20)
#There are 74 missing values in the dataset.Missing values are filled with zeroes in the data set for the purpose of error handling.
#There are no duplicate values in the dataset
#Mean is 71.71621621621621
#Median is 68.0
#Standard deviation is 20.705052173004944
#The distribution of runs and wickets is 50% each.
#Mumbai has the highest high score when compared with other teams.Mumbai is the best team in terms of high score.
#There are afew outliers which are to be remove by me.
#Wankhede Stadium, Mumbai  gave the highset number of wins while Narendra Modi Stadium, Ahmedabad  gave the least number of wins.This shows that venue or stadium impacts the win or loss to some extent.
#Yuzvendra Chahal  is the best bowler for 5 times.

match_id	date	venue	team1	team2	stage	toss_winner	toss_decision	first_ings_score	first_ings_wkts	second_ings_score	second_ings_wkts	match_winner	won_by	margin	player_of_the_match	top_scorer	highscore	best_bowling	best_bowling_figure.These are the columns in a datset.give me python code for the following question.explain correlations between different variable susing statistical analysis examine hoew different match condition like toss decisions,inning scores or venue impact the match outcomes