# -*- coding: utf-8 -*-
"""LVADSUSR147___DUVVAPU CHINNI VAISHNAVI___.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hX7tl4pOfatqj4OnfwUEAmbXrHiy68sL
"""

#1
import numpy as np
b=[1,2,3,4,5,6]
a=np.array(b)
min_=np.min(a)
max_=np.max(a)
sum_=np.sum(a)
mean_=np.mean(a)
std_=np.std(a)
print("Min value of array:",min_)
print("Max value of array:",max_)
print("Sum value of array:",sum_)
print("Mean value of array:",mean_)
print("Standard deviation value of array:",std_)

#2
import numpy as np
health_data=np.array([[160,70,30],
                      [165,65,35],
                     [175,70,40]])
print("Given data is",health_data)
Mean_value=np.mean(health_data)
std_value=np.std(health_data)
print("Mean of given data is",Mean_value)
print("Standard deviation of given data is ",std_value)
def normalization(health_data):
  pass
normalization(health_data)

#3
import numpy as np
a=np.array([[10,20,30,40,50],
            [50,54,30,20,10],
            [60,70,80,90,-1],
            [90,70,80,-1,30]])
b=np.where(a>-1,a,0)
print(b)
for student in a:
  for i in range(len(student)):
    if not(student[-1]==-1) and not(student[-2]==-1) and not(student[-3]==-1):
      x=sum(student[-3:])
  print("Average score in last 3 subjects for four students is")
  print(x)

#4
import numpy as np
temp_readings=np.linspace(15,25,24)
print("The temperature readings collected from sensor data which are between 15 degree celcius and 25 degree celcius are:",)
print(temp_readings)

#5
import numpy as np
daily_closing_prices=np.array([100,102,98,105,107,110,108,112,115118,120])
window_size=5
a=np.split(daily_closing_prices,2)
print(a)
z=[]
for i in a:
  x=np.mean(i)
  z.append(x)
  print(x)
sum=0
for i in z:
  sum=sum+i
print("Moving average for a window of 5 is",sum)

#6
import numpy as np
import random
mean_vector=[0,0]
covariance_matrix=[[1,0.5],[0.5,2]]
sample_distribution=np.random.rand(100)
print("Synthetic data is")
print(sample_distribution)

#7
import numpy as np
properties_matrix=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
arr=properties_matrix.reshape(3,3)
print("The 3*3 matrix dimensions are:",properties_matrix.shape)
determinant=np.linalg.det(properties_matrix)
print("The determinant of matrix is",determinant)

#8
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
bool_array=(arr>5)
print(bool_array)
filtered_array=arr[bool_array]
print("The numbers greater than 5 are:",filtered_array)
b=arr[bool_array==False]
print("The elemts which are less than or equal to 5 are:",b)

#9
import pandas as pd
import warnings as wr
wr.filterwarnings('ignore')
data={"Name":["Alice","Bob","Charlie","David","Eve","Frank","Grace"],
      "Age":[20,30,35,40,45,50,55],
      "City":["New York","Los Angeles","Chicago","Houston","Phoenix","Miami","Boston"],
      "Department":["HR","IT","Finance","Marketing","Sales","IT","HR"]
      }
df=pd.DataFrame(data)
print(df)
print("-------")
#df["Name","City"]=df[df["Name","City"] in data["Name","City"] if df["Age"]<45 and df["Department"]!="HR"]
print(df["Name","City"])

#10
import pandas as pd
import warnings as wr
wr.filterwarnings('ignore')
data={"DEpartment":["Electronics","Electronics","Electronics","Clothing","Clothing","Home Goods"],
      "Salesperson":["Alice","Bob","Charlie","David","Eve"],
       "sales":[70000,50000,30000,40000,60000]}
df=pd.DataFrame(data)
print(df)

#11
import pandas as pd
import numpy as np
import warnings as wr
wr.filterwarnings('ignore')

#12
import pandas as pd
import numpy as np
import warnings as wr
wr.filterwarnings('ignore')

#13
import pandas as pd
import warnings as wr
wr.filterwarnings('ignore')
df=pd.read_csv('/content/sample_data/Q13_sports_team_stats.csv')
print(df)
avg=df["Wins"].mean()
print("The average score is",avg)

#14
import pandas as pd
import warnings as wr
wr.filterwarnings('ignore')
b=pd.read_csv('/content/sample_data/Q14_customer_purchases.csv')
print(b)

#15
import pandas as pd
import warnings as wr
wr.filterwarnings('ignore')
c=pd.read_csv('/content/sample_data/Q15_student_grades.csv')
print(c)